In [18]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [19]:
reviews = ['nice food', 'amazing restaurant', 'too good', 'just loved it!', 'will go again', 'horrible food', 'never go there', 'poor services', 'needs improvements', 'poor quality']
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [20]:
one_hot("amazing restaurant", 30)

[25, 4]

In [21]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[11, 2],
 [25, 4],
 [3, 3],
 [3, 22, 24],
 [11, 17, 20],
 [22, 2],
 [9, 17, 16],
 [4, 11],
 [5, 21],
 [4, 26]]

In [22]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[11,  2,  0,  0],
       [25,  4,  0,  0],
       [ 3,  3,  0,  0],
       [ 3, 22, 24,  0],
       [11, 17, 20,  0],
       [22,  2,  0,  0],
       [ 9, 17, 16,  0],
       [ 4, 11,  0,  0],
       [ 5, 21,  0,  0],
       [ 4, 26,  0,  0]], dtype=int32)

In [23]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [24]:
X = padded_reviews
y = sentiment

In [25]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [26]:
model.fit(X, y, epochs=50, verbose=0)

In [27]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 221ms/step - accuracy: 1.0000 - loss: 0.6314


1.0

In [29]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [30]:
weights[11]

array([ 0.03752142, -0.10902479,  0.00270914,  0.0294656 ,  0.03122192],
      dtype=float32)

In [32]:
weights[25]

array([ 0.04618415, -0.06303918,  0.09041008, -0.03373043,  0.08743358],
      dtype=float32)